version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "always"
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    ports:
      - "2113:2113"  # Admin HTTP
      - "1113:1113"  # TCP for EventStore communication
    environment:
      - EVENTSTORE_DB=/var/lib/eventstore/db
      - EVENTSTORE_LOG=/var/lib/eventstore/log
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
    volumes:
      - eventstore-data:/var/lib/eventstore
    restart: unless-stopped

volumes:
  eventstore-data:
    driver: local
